import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/context/auth-context';

type Log = { id: string; action: string; entityType?: string; createdAt: string; changes?: Record<string, unknown> };
const labels: Record<string, string> = { LISTING_CREATED: 'İlan oluşturuldu', LISTING_UPDATED: 'İlan güncellendi', LISTING_DELETED: 'İlan silindi', ORGANIZATION_APPLICATION_CREATED: 'Kurumsal başvuru oluşturuldu', ORGANIZATION_APPLICATION_EDITED: 'Kurumsal başvuru düzenlendi', PORTAL_ACCOUNT_CREATED: 'Portal hesabı eklendi', PORTAL_ACCOUNT_CONNECTION_TESTED: 'Portal bağlantısı test edildi' };
export default function ActivityScreen() { const { request } = useAuth(); const [items, setItems] = useState<Log[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); try { const r = await request('audit-logs'); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(typeof p.message === 'string' ? p.message : 'Aktiviteler yüklenemedi.'); setItems(Array.isArray(p) ? p : p.data ?? []); } catch (e) { setError(e instanceof Error ? e.message : 'Aktiviteler yüklenemedi.'); } finally { setLoading(false); setRefreshing(false); } }, [request]); useEffect(() => { void load(); }, [load]); return <View style={styles.root}><Text style={styles.eyebrow}>TAKİP</Text><Text style={styles.title}>Aktivite</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{loading ? <ActivityIndicator color={Colors.light.primary} size="large" /> : <FlatList contentContainerStyle={styles.list} data={items} keyExtractor={(item) => item.id} refreshControl={<RefreshControl colors={[Colors.light.primary]} onRefresh={() => void load(true)} refreshing={refreshing} />} ListEmptyComponent={<Text style={styles.empty}>Henüz aktivite bulunmuyor.</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.action}>{labels[item.action] ?? 'Hesap hareketi'}</Text><Text style={styles.muted}>{new Date(item.createdAt).toLocaleString('tr-TR')}</Text></View>} />}</View>; }
const styles = StyleSheet.create({ root: { backgroundColor: Colors.light.background, flex: 1, padding: 20, paddingTop: 30 }, eyebrow: { color: Colors.light.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, title: { color: Colors.light.text, fontSize: 27, fontWeight: '800', marginTop: 5 }, list: { paddingVertical: 20 }, card: { backgroundColor: Colors.light.card, borderColor: Colors.light.border, borderRadius: 15, borderWidth: 1, marginBottom: 10, padding: 15 }, action: { color: Colors.light.text, fontSize: 15, fontWeight: '800' }, muted: { color: Colors.light.muted, fontSize: 12, marginTop: 5 }, empty: { color: Colors.light.muted, padding: 25, textAlign: 'center' }, error: { backgroundColor: '#FFF0EE', borderRadius: 12, color: Colors.light.error, marginTop: 16, padding: 12 } });
