import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/context/auth-context';

type Listing = { id: string; title: string; listingNo: string; city: string; district: string; status: string; price: number | string; currency?: string; media?: Array<{ url?: string; isCover?: boolean }>; updatedAt?: string; publications?: Array<{ status?: string }> };

export default function ListingsScreen() {
  const { request } = useAuth();
  const router = useRouter();
  const [items, setItems] = useState<Listing[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState('');
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); setError(''); try { const response = await request('listings'); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof payload.message === 'string' ? payload.message : 'İlanlar yüklenemedi.'); setItems(Array.isArray(payload) ? payload : payload.data ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'İlanlar yüklenemedi.'); } finally { setLoading(false); setRefreshing(false); } }, [request]);
  useEffect(() => { void load(); }, [load]);
  return <View style={styles.root}><View style={styles.header}><View><Text style={styles.eyebrow}>PORTFÖY</Text><Text style={styles.title}>İlanlar</Text></View><Pressable onPress={() => router.push('/(tabs)/new-listing')} style={styles.add}><Ionicons color="#FFF" name="add" size={22} /></Pressable></View>{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Tekrar Dene</Text></Pressable></View> : null}{loading ? <ActivityIndicator color={Colors.light.primary} size="large" /> : <FlatList contentContainerStyle={styles.list} data={items} keyExtractor={(item) => item.id} refreshControl={<RefreshControl colors={[Colors.light.primary]} onRefresh={() => void load(true)} refreshing={refreshing} />} ListEmptyComponent={<View style={styles.empty}><Ionicons color={Colors.light.primary} name="business-outline" size={34} /><Text style={styles.emptyTitle}>Henüz ilan yok</Text><Text style={styles.muted}>İlk ilanınızı Yeni İlan sekmesinden oluşturun.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => router.push(`/listings/${item.id}`)} style={styles.card}><View style={styles.cardTop}><View style={styles.icon}><Ionicons color={Colors.light.primary} name="home-outline" size={22} /></View><View style={styles.flex}><Text numberOfLines={1} style={styles.cardTitle}>{item.title}</Text><Text style={styles.muted}>{item.listingNo} · {item.city}, {item.district}</Text></View><Text style={styles.badge}>{item.status}</Text></View><Text style={styles.price}>{Number(item.price).toLocaleString('tr-TR')} {item.currency ?? 'TL'}</Text><Text style={styles.muted}>Güncelleme: {item.updatedAt ? new Date(item.updatedAt).toLocaleDateString('tr-TR') : '—'} · Yayın: {item.publications?.length ?? 0}</Text></Pressable>} />}</View>;
}

const styles = StyleSheet.create({ root: { backgroundColor: Colors.light.background, flex: 1, padding: 20, paddingTop: 30 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 }, eyebrow: { color: Colors.light.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, title: { color: Colors.light.text, fontSize: 27, fontWeight: '800', marginTop: 4 }, add: { alignItems: 'center', backgroundColor: Colors.light.primary, borderRadius: 22, height: 44, justifyContent: 'center', width: 44 }, list: { paddingBottom: 24 }, card: { backgroundColor: Colors.light.card, borderColor: Colors.light.border, borderRadius: 17, borderWidth: 1, marginBottom: 12, padding: 15 }, cardTop: { alignItems: 'center', flexDirection: 'row', gap: 11 }, icon: { alignItems: 'center', backgroundColor: Colors.light.soft, borderRadius: 12, height: 44, justifyContent: 'center', width: 44 }, flex: { flex: 1 }, cardTitle: { color: Colors.light.text, fontSize: 15, fontWeight: '800' }, muted: { color: Colors.light.muted, fontSize: 12, lineHeight: 18, marginTop: 3 }, badge: { backgroundColor: Colors.light.soft, borderRadius: 8, color: Colors.light.primary, fontSize: 10, fontWeight: '800', paddingHorizontal: 7, paddingVertical: 5 }, price: { color: Colors.light.text, fontSize: 18, fontWeight: '800', marginLeft: 55, marginTop: 12 }, empty: { alignItems: 'center', backgroundColor: Colors.light.card, borderColor: Colors.light.border, borderRadius: 18, borderWidth: 1, padding: 30 }, emptyTitle: { color: Colors.light.text, fontSize: 17, fontWeight: '800', marginTop: 10 }, error: { alignItems: 'center', backgroundColor: '#FFF0EE', borderRadius: 14, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16, padding: 13 }, errorText: { color: Colors.light.error, flex: 1, fontSize: 13 }, retry: { color: Colors.light.primary, fontWeight: '800', marginLeft: 10 } });
