import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/context/auth-context';

type Listing = { id: string; title: string; listingNo: string; city: string; district: string; status: string; price: number | string };
export default function ListingsScreen() { const { request } = useAuth(); const [items, setItems] = useState<Listing[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { request('listings').then(async (response) => { if (response.ok) { const payload = await response.json(); setItems(Array.isArray(payload) ? payload : payload.data ?? []); } }).finally(() => setLoading(false)); }, [request]); return <View style={styles.root}><View style={styles.header}><View><Text style={styles.eyebrow}>PORTFÖY</Text><Text style={styles.title}>İlanlar</Text></View><Pressable style={styles.add}><Ionicons color="#FFF" name="add" size={22} /></Pressable></View>{loading ? <ActivityIndicator color={Colors.light.primary} size="large" /> : <FlatList contentContainerStyle={styles.list} data={items} keyExtractor={(item) => item.id} ListEmptyComponent={<View style={styles.empty}><Ionicons color={Colors.light.primary} name="business-outline" size={34} /><Text style={styles.emptyTitle}>Henüz ilan yok</Text><Text style={styles.muted}>İlk ilanınızı yayınlamak için Yeni İlan sekmesini kullanın.</Text></View>} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View style={styles.icon}><Ionicons color={Colors.light.primary} name="home-outline" size={22} /></View><View style={styles.flex}><Text numberOfLines={1} style={styles.cardTitle}>{item.title}</Text><Text style={styles.muted}>{item.listingNo} · {item.city}, {item.district}</Text></View><Text style={styles.badge}>{item.status}</Text></View><Text style={styles.price}>{typeof item.price === 'number' ? `${item.price.toLocaleString('tr-TR')} ₺` : item.price}</Text></View>} />}</View>; }
const styles = StyleSheet.create({ root: { backgroundColor: Colors.light.background, flex: 1, padding: 20, paddingTop: 30 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 }, eyebrow: { color: Colors.light.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, title: { color: Colors.light.text, fontSize: 27, fontWeight: '800', marginTop: 4 }, add: { alignItems: 'center', backgroundColor: Colors.light.primary, borderRadius: 22, height: 44, justifyContent: 'center', width: 44 }, list: { paddingBottom: 24 }, card: { backgroundColor: Colors.light.card, borderColor: Colors.light.border, borderRadius: 17, borderWidth: 1, marginBottom: 12, padding: 15 }, cardTop: { alignItems: 'center', flexDirection: 'row', gap: 11 }, icon: { alignItems: 'center', backgroundColor: Colors.light.soft, borderRadius: 12, height: 44, justifyContent: 'center', width: 44 }, flex: { flex: 1 }, cardTitle: { color: Colors.light.text, fontSize: 15, fontWeight: '800' }, muted: { color: Colors.light.muted, fontSize: 12, lineHeight: 18, marginTop: 3 }, badge: { backgroundColor: Colors.light.soft, borderRadius: 8, color: Colors.light.primary, fontSize: 10, fontWeight: '800', paddingHorizontal: 7, paddingVertical: 5 }, price: { color: Colors.light.text, fontSize: 18, fontWeight: '800', marginLeft: 55, marginTop: 12 }, empty: { alignItems: 'center', backgroundColor: Colors.light.card, borderColor: Colors.light.border, borderRadius: 18, borderWidth: 1, padding: 30 }, emptyTitle: { color: Colors.light.text, fontSize: 17, fontWeight: '800', marginTop: 10 } });
