// @ts-nocheck
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ComponentProps, ReactNode } from 'react';
import { useRouter } from 'expo-router';
import { getDistrictsByCity, getHousingTypesForPropertyType, getTurkeyCities } from '@tiklayayinla/shared-types';
import { Colors } from '@/constants/theme';
import { useAuth } from '@/context/auth-context';
import VehicleListingForm from '@/components/VehicleListingForm';

type Form = Record<string, string>;
const propertyTypes = ['APARTMENT', 'HOUSE', 'VILLA', 'LAND', 'COMMERCIAL', 'OFFICE', 'OTHER'];
const listingTypes = ['SALE', 'RENT'];
const currencies = ['TRY', 'USD', 'EUR'];

export default function NewListingScreen() {
  const { request } = useAuth(); const router = useRouter();
  const [form, setForm] = useState<Form>({ currency: 'TRY', listingType: 'SALE', propertyType: 'APARTMENT' });
  const [profile, setProfile] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [picker, setPicker] = useState<keyof Form | null>(null);
  useEffect(() => { void request('users/me').then(async (r) => { if (r.ok) setProfile(await r.json()); }); }, [request]);
  const districts = useMemo(() => getDistrictsByCity(form.city ?? ''), [form.city]); const housingTypes = getHousingTypesForPropertyType(form.propertyType ?? 'APARTMENT');
  function set(key: string, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  function chooseCity(value: string) { setForm((current) => ({ ...current, city: value, district: '' })); }
  async function submit() {
    setError(''); const required = ['title', 'description', 'price', 'city', 'district', 'address', 'propertyType'];
    if (required.some((key) => !form[key]?.trim())) return setError('Lütfen zorunlu alanları doldurun.');
    if (form.description.trim().length < 20) return setError('Açıklama en az 20 karakter olmalıdır.');
    setLoading(true);
    try {
      const residentialDetails = { ...(form.housingType && { housingType: form.housingType }), ...(form.roomCount && { roomCount: form.roomCount }), ...(form.grossArea && { grossArea: Number(form.grossArea) }), ...(form.netArea && { netArea: Number(form.netArea) }) };
      const body = { title: form.title.trim(), description: form.description.trim(), price: Number(form.price), currency: form.currency, listingType: form.listingType, propertyType: form.propertyType, city: form.city, district: form.district, neighborhood: form.neighborhood?.trim() || undefined, address: form.address.trim(), residentialDetails };
      const response = await request('listings', { method: 'POST', body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(typeof payload.message === 'string' ? payload.message : 'İlan oluşturulamadı.'); router.push(`/listings/${payload.id}`);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'İlan oluşturulamadı.'); } finally { setLoading(false); }
  }
  if (profile?.organizationType === 'AUTO_DEALER') return <VehicleListingForm initialProfile={profile} />;
  const options = picker === 'city' ? getTurkeyCities().map((x) => x.name) : picker === 'district' ? districts : picker === 'housingType' ? housingTypes : picker === 'propertyType' ? propertyTypes : picker === 'listingType' ? listingTypes : currencies;
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.root}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>YAYINLA</Text><Text style={styles.title}>Yeni İlan</Text><Text style={styles.subtitle}>İlan bilgilerini gerçek hesabınıza kaydedin.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<Section title="Temel Bilgiler"><Input label="İlan başlığı" required value={form.title} onChangeText={(v) => set('title', v)} /><Input label="Açıklama" required multiline value={form.description} onChangeText={(v) => set('description', v)} /><Input label="Fiyat" required keyboardType="decimal-pad" value={form.price} onChangeText={(v) => set('price', v.replace(',', '.'))} /></Section><Section title="İlan Tipi"><Choice label="Para birimi" value={form.currency} onPress={() => setPicker('currency')} /><Choice label="İlan tipi" value={form.listingType} onPress={() => setPicker('listingType')} /><Choice label="Gayrimenkul tipi" value={form.propertyType} onPress={() => setPicker('propertyType')} /><Choice label="Konut tipi" value={form.housingType} onPress={() => setPicker('housingType')} /></Section><Section title="Konum"><Choice label="İl" value={form.city} placeholder="İl seçiniz" onPress={() => setPicker('city')} /><Choice label="İlçe" value={form.district} placeholder="İlçe seçiniz" disabled={!form.city} onPress={() => setPicker('district')} /><Input label="Mahalle" value={form.neighborhood} onChangeText={(v) => set('neighborhood', v)} /><Input label="Açık adres" required value={form.address} onChangeText={(v) => set('address', v)} /></Section><Section title="Konut Özellikleri"><Input label="Oda sayısı" value={form.roomCount} onChangeText={(v) => set('roomCount', v)} /><Input label="Brüt alan (m²)" keyboardType="decimal-pad" value={form.grossArea} onChangeText={(v) => set('grossArea', v)} /><Input label="Net alan (m²)" keyboardType="decimal-pad" value={form.netArea} onChangeText={(v) => set('netArea', v)} /></Section><Pressable disabled={loading} onPress={() => void submit()} style={styles.button}>{loading ? <ActivityIndicator color="#FFF" /> : <Text style={styles.buttonText}>İlanı Oluştur</Text>}</Pressable></ScrollView><PickerModal field={picker} options={options} onClose={() => setPicker(null)} onSelect={(value) => { if (picker === 'city') chooseCity(value); else if (picker) set(picker, value); setPicker(null); }} /></KeyboardAvoidingView>;
}
function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Input({ label, required, multiline, ...props }: { label: string; required?: boolean; multiline?: boolean } & ComponentProps<typeof TextInput>) { return <View style={styles.field}><Text style={styles.label}>{label}{required ? ' *' : ''}</Text><TextInput {...props} multiline={multiline} placeholder={label} placeholderTextColor={Colors.light.muted} style={[styles.input, multiline && styles.textarea]} /></View>; }
function Choice({ label, value, placeholder = 'Seçiniz', disabled, onPress }: { label: string; value?: string; placeholder?: string; disabled?: boolean; onPress: () => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><Pressable disabled={disabled} onPress={onPress} style={styles.choice}><Text style={value ? styles.choiceText : styles.placeholder}>{value || placeholder}</Text><Text style={styles.chevron}>⌄</Text></Pressable></View>; }
function PickerModal({ field, options, onClose, onSelect }: { field: string | null; options: string[]; onClose: () => void; onSelect: (value: string) => void }) { return <Modal animationType="slide" transparent visible={Boolean(field)} onRequestClose={onClose}><Pressable onPress={onClose} style={styles.modalBackdrop}><View style={styles.modal}><Text style={styles.modalTitle}>Seçiniz</Text><ScrollView>{options.map((option) => <Pressable key={option} onPress={() => onSelect(option)} style={styles.option}><Text style={styles.optionText}>{option}</Text></Pressable>)}</ScrollView></View></Pressable></Modal>; }
const styles = StyleSheet.create({ root: { backgroundColor: Colors.light.background, flex: 1 }, content: { padding: 20, paddingBottom: 36 }, center: { alignItems: 'center', backgroundColor: Colors.light.background, flex: 1, justifyContent: 'center', padding: 28 }, eyebrow: { color: Colors.light.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, title: { color: Colors.light.text, fontSize: 27, fontWeight: '800', marginTop: 5 }, subtitle: { color: Colors.light.secondary, fontSize: 14, marginTop: 7 }, error: { backgroundColor: '#FFF0EE', borderRadius: 12, color: Colors.light.error, marginTop: 16, padding: 12 }, section: { backgroundColor: Colors.light.card, borderColor: Colors.light.border, borderRadius: 18, borderWidth: 1, marginTop: 18, padding: 16 }, sectionTitle: { color: Colors.light.text, fontSize: 17, fontWeight: '800', marginBottom: 8 }, field: { marginTop: 10 }, label: { color: Colors.light.secondary, fontSize: 12, fontWeight: '700', marginBottom: 6 }, input: { backgroundColor: '#F7F8F8', borderColor: Colors.light.border, borderRadius: 11, borderWidth: 1, color: Colors.light.text, minHeight: 48, paddingHorizontal: 13, paddingVertical: 12 }, textarea: { minHeight: 110, textAlignVertical: 'top' }, choice: { alignItems: 'center', backgroundColor: '#F7F8F8', borderColor: Colors.light.border, borderRadius: 11, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 48, paddingHorizontal: 13 }, choiceText: { color: Colors.light.text }, placeholder: { color: Colors.light.muted }, chevron: { color: Colors.light.primary, fontSize: 20 }, button: { alignItems: 'center', backgroundColor: Colors.light.primary, borderRadius: 14, marginTop: 22, minHeight: 54, justifyContent: 'center' }, buttonText: { color: '#FFF', fontSize: 15, fontWeight: '800' }, modalBackdrop: { backgroundColor: 'rgba(0,0,0,.35)', flex: 1, justifyContent: 'flex-end' }, modal: { backgroundColor: Colors.light.card, borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '75%', padding: 20 }, modalTitle: { color: Colors.light.text, fontSize: 18, fontWeight: '800', marginBottom: 8 }, option: { borderBottomColor: Colors.light.border, borderBottomWidth: 1, paddingVertical: 15 }, optionText: { color: Colors.light.text, fontSize: 15 } });
