'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';

export function ForgotPasswordForm() {
  const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [sent, setSent] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); setMessage(null); setLoading(true); try { const action = sent ? 'reset-password' : 'forgot-password'; const body = sent ? { email: email.trim().toLowerCase(), code, newPassword: password, confirmPassword: confirm } : { email: email.trim().toLowerCase() }; const response = await fetch(`/api/auth/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error((payload as { message?: string }).message ?? 'İşlem tamamlanamadı.'); if (!sent) { setSent(true); setMessage('Kod gönderildi. E-postanızı kontrol edin.'); } else { setMessage('Şifreniz yenilendi.'); } } catch (e) { setError(e instanceof Error ? e.message : 'İşlem tamamlanamadı.'); } finally { setLoading(false); } }
  return <form className="mt-6 space-y-4" onSubmit={submit}><label className="grid gap-2 text-sm font-semibold">E-posta<input className="rounded-lg border p-3 font-normal" type="email" required value={email} onChange={e=>setEmail(e.target.value)} disabled={sent} /></label>{sent && <><label className="grid gap-2 text-sm font-semibold">Kod<input className="rounded-lg border p-3 font-normal" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} /></label><label className="grid gap-2 text-sm font-semibold">Yeni şifre<input className="rounded-lg border p-3 font-normal" type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} /></label><label className="grid gap-2 text-sm font-semibold">Yeni şifre tekrar<input className="rounded-lg border p-3 font-normal" type="password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)} /></label></>}{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<button className="w-full rounded-xl bg-teal-700 px-4 py-3 font-semibold text-white disabled:opacity-50" disabled={loading}>{loading ? 'Bekleyin...' : sent ? 'Şifreyi yenile' : 'Kod gönder'}</button><Link className="block text-center text-sm font-semibold text-teal-700" href="/login">Girişe dön</Link></form>;
}
