-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'EIDS_AUTHORIZATION_STARTED';
ALTER TYPE "AuditAction" ADD VALUE 'EIDS_AUTHORIZATION_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'EIDS_CALLBACK_FAILED';
